
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Lanchonete` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Lanchonete
 * 
 */
export type LanchoneteModel = runtime.Types.Result.DefaultSelection<Prisma.$LanchonetePayload>

export type AggregateLanchonete = {
  _count: LanchoneteCountAggregateOutputType | null
  _avg: LanchoneteAvgAggregateOutputType | null
  _sum: LanchoneteSumAggregateOutputType | null
  _min: LanchoneteMinAggregateOutputType | null
  _max: LanchoneteMaxAggregateOutputType | null
}

export type LanchoneteAvgAggregateOutputType = {
  id: number | null
}

export type LanchoneteSumAggregateOutputType = {
  id: number | null
}

export type LanchoneteMinAggregateOutputType = {
  id: number | null
  nome: string | null
  imagemFundo: string | null
  imagemLogo: string | null
  utualizadaEm: Date | null
}

export type LanchoneteMaxAggregateOutputType = {
  id: number | null
  nome: string | null
  imagemFundo: string | null
  imagemLogo: string | null
  utualizadaEm: Date | null
}

export type LanchoneteCountAggregateOutputType = {
  id: number
  nome: number
  imagemFundo: number
  imagemLogo: number
  utualizadaEm: number
  _all: number
}


export type LanchoneteAvgAggregateInputType = {
  id?: true
}

export type LanchoneteSumAggregateInputType = {
  id?: true
}

export type LanchoneteMinAggregateInputType = {
  id?: true
  nome?: true
  imagemFundo?: true
  imagemLogo?: true
  utualizadaEm?: true
}

export type LanchoneteMaxAggregateInputType = {
  id?: true
  nome?: true
  imagemFundo?: true
  imagemLogo?: true
  utualizadaEm?: true
}

export type LanchoneteCountAggregateInputType = {
  id?: true
  nome?: true
  imagemFundo?: true
  imagemLogo?: true
  utualizadaEm?: true
  _all?: true
}

export type LanchoneteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lanchonete to aggregate.
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lanchonetes to fetch.
   */
  orderBy?: Prisma.LanchoneteOrderByWithRelationInput | Prisma.LanchoneteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LanchoneteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lanchonetes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lanchonetes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Lanchonetes
  **/
  _count?: true | LanchoneteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LanchoneteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LanchoneteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LanchoneteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LanchoneteMaxAggregateInputType
}

export type GetLanchoneteAggregateType<T extends LanchoneteAggregateArgs> = {
      [P in keyof T & keyof AggregateLanchonete]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLanchonete[P]>
    : Prisma.GetScalarType<T[P], AggregateLanchonete[P]>
}




export type LanchoneteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LanchoneteWhereInput
  orderBy?: Prisma.LanchoneteOrderByWithAggregationInput | Prisma.LanchoneteOrderByWithAggregationInput[]
  by: Prisma.LanchoneteScalarFieldEnum[] | Prisma.LanchoneteScalarFieldEnum
  having?: Prisma.LanchoneteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LanchoneteCountAggregateInputType | true
  _avg?: LanchoneteAvgAggregateInputType
  _sum?: LanchoneteSumAggregateInputType
  _min?: LanchoneteMinAggregateInputType
  _max?: LanchoneteMaxAggregateInputType
}

export type LanchoneteGroupByOutputType = {
  id: number
  nome: string
  imagemFundo: string | null
  imagemLogo: string | null
  utualizadaEm: Date
  _count: LanchoneteCountAggregateOutputType | null
  _avg: LanchoneteAvgAggregateOutputType | null
  _sum: LanchoneteSumAggregateOutputType | null
  _min: LanchoneteMinAggregateOutputType | null
  _max: LanchoneteMaxAggregateOutputType | null
}

type GetLanchoneteGroupByPayload<T extends LanchoneteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LanchoneteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LanchoneteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LanchoneteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LanchoneteGroupByOutputType[P]>
      }
    >
  >



export type LanchoneteWhereInput = {
  AND?: Prisma.LanchoneteWhereInput | Prisma.LanchoneteWhereInput[]
  OR?: Prisma.LanchoneteWhereInput[]
  NOT?: Prisma.LanchoneteWhereInput | Prisma.LanchoneteWhereInput[]
  id?: Prisma.IntFilter<"Lanchonete"> | number
  nome?: Prisma.StringFilter<"Lanchonete"> | string
  imagemFundo?: Prisma.StringNullableFilter<"Lanchonete"> | string | null
  imagemLogo?: Prisma.StringNullableFilter<"Lanchonete"> | string | null
  utualizadaEm?: Prisma.DateTimeFilter<"Lanchonete"> | Date | string
}

export type LanchoneteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  imagemFundo?: Prisma.SortOrderInput | Prisma.SortOrder
  imagemLogo?: Prisma.SortOrderInput | Prisma.SortOrder
  utualizadaEm?: Prisma.SortOrder
}

export type LanchoneteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.LanchoneteWhereInput | Prisma.LanchoneteWhereInput[]
  OR?: Prisma.LanchoneteWhereInput[]
  NOT?: Prisma.LanchoneteWhereInput | Prisma.LanchoneteWhereInput[]
  nome?: Prisma.StringFilter<"Lanchonete"> | string
  imagemFundo?: Prisma.StringNullableFilter<"Lanchonete"> | string | null
  imagemLogo?: Prisma.StringNullableFilter<"Lanchonete"> | string | null
  utualizadaEm?: Prisma.DateTimeFilter<"Lanchonete"> | Date | string
}, "id">

export type LanchoneteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  imagemFundo?: Prisma.SortOrderInput | Prisma.SortOrder
  imagemLogo?: Prisma.SortOrderInput | Prisma.SortOrder
  utualizadaEm?: Prisma.SortOrder
  _count?: Prisma.LanchoneteCountOrderByAggregateInput
  _avg?: Prisma.LanchoneteAvgOrderByAggregateInput
  _max?: Prisma.LanchoneteMaxOrderByAggregateInput
  _min?: Prisma.LanchoneteMinOrderByAggregateInput
  _sum?: Prisma.LanchoneteSumOrderByAggregateInput
}

export type LanchoneteScalarWhereWithAggregatesInput = {
  AND?: Prisma.LanchoneteScalarWhereWithAggregatesInput | Prisma.LanchoneteScalarWhereWithAggregatesInput[]
  OR?: Prisma.LanchoneteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LanchoneteScalarWhereWithAggregatesInput | Prisma.LanchoneteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Lanchonete"> | number
  nome?: Prisma.StringWithAggregatesFilter<"Lanchonete"> | string
  imagemFundo?: Prisma.StringNullableWithAggregatesFilter<"Lanchonete"> | string | null
  imagemLogo?: Prisma.StringNullableWithAggregatesFilter<"Lanchonete"> | string | null
  utualizadaEm?: Prisma.DateTimeWithAggregatesFilter<"Lanchonete"> | Date | string
}

export type LanchoneteCreateInput = {
  id?: number
  nome: string
  imagemFundo?: string | null
  imagemLogo?: string | null
  utualizadaEm?: Date | string
}

export type LanchoneteUncheckedCreateInput = {
  id?: number
  nome: string
  imagemFundo?: string | null
  imagemLogo?: string | null
  utualizadaEm?: Date | string
}

export type LanchoneteUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  imagemFundo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagemLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  utualizadaEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LanchoneteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  imagemFundo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagemLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  utualizadaEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LanchoneteCreateManyInput = {
  id?: number
  nome: string
  imagemFundo?: string | null
  imagemLogo?: string | null
  utualizadaEm?: Date | string
}

export type LanchoneteUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  imagemFundo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagemLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  utualizadaEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LanchoneteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  imagemFundo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagemLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  utualizadaEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LanchoneteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  imagemFundo?: Prisma.SortOrder
  imagemLogo?: Prisma.SortOrder
  utualizadaEm?: Prisma.SortOrder
}

export type LanchoneteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type LanchoneteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  imagemFundo?: Prisma.SortOrder
  imagemLogo?: Prisma.SortOrder
  utualizadaEm?: Prisma.SortOrder
}

export type LanchoneteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  imagemFundo?: Prisma.SortOrder
  imagemLogo?: Prisma.SortOrder
  utualizadaEm?: Prisma.SortOrder
}

export type LanchoneteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type LanchoneteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  imagemFundo?: boolean
  imagemLogo?: boolean
  utualizadaEm?: boolean
}, ExtArgs["result"]["lanchonete"]>

export type LanchoneteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  imagemFundo?: boolean
  imagemLogo?: boolean
  utualizadaEm?: boolean
}, ExtArgs["result"]["lanchonete"]>

export type LanchoneteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  imagemFundo?: boolean
  imagemLogo?: boolean
  utualizadaEm?: boolean
}, ExtArgs["result"]["lanchonete"]>

export type LanchoneteSelectScalar = {
  id?: boolean
  nome?: boolean
  imagemFundo?: boolean
  imagemLogo?: boolean
  utualizadaEm?: boolean
}

export type LanchoneteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "imagemFundo" | "imagemLogo" | "utualizadaEm", ExtArgs["result"]["lanchonete"]>

export type $LanchonetePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Lanchonete"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nome: string
    imagemFundo: string | null
    imagemLogo: string | null
    utualizadaEm: Date
  }, ExtArgs["result"]["lanchonete"]>
  composites: {}
}

export type LanchoneteGetPayload<S extends boolean | null | undefined | LanchoneteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LanchonetePayload, S>

export type LanchoneteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LanchoneteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LanchoneteCountAggregateInputType | true
  }

export interface LanchoneteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Lanchonete'], meta: { name: 'Lanchonete' } }
  /**
   * Find zero or one Lanchonete that matches the filter.
   * @param {LanchoneteFindUniqueArgs} args - Arguments to find a Lanchonete
   * @example
   * // Get one Lanchonete
   * const lanchonete = await prisma.lanchonete.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LanchoneteFindUniqueArgs>(args: Prisma.SelectSubset<T, LanchoneteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lanchonete that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LanchoneteFindUniqueOrThrowArgs} args - Arguments to find a Lanchonete
   * @example
   * // Get one Lanchonete
   * const lanchonete = await prisma.lanchonete.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LanchoneteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LanchoneteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lanchonete that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteFindFirstArgs} args - Arguments to find a Lanchonete
   * @example
   * // Get one Lanchonete
   * const lanchonete = await prisma.lanchonete.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LanchoneteFindFirstArgs>(args?: Prisma.SelectSubset<T, LanchoneteFindFirstArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lanchonete that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteFindFirstOrThrowArgs} args - Arguments to find a Lanchonete
   * @example
   * // Get one Lanchonete
   * const lanchonete = await prisma.lanchonete.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LanchoneteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LanchoneteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Lanchonetes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Lanchonetes
   * const lanchonetes = await prisma.lanchonete.findMany()
   * 
   * // Get first 10 Lanchonetes
   * const lanchonetes = await prisma.lanchonete.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lanchoneteWithIdOnly = await prisma.lanchonete.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LanchoneteFindManyArgs>(args?: Prisma.SelectSubset<T, LanchoneteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lanchonete.
   * @param {LanchoneteCreateArgs} args - Arguments to create a Lanchonete.
   * @example
   * // Create one Lanchonete
   * const Lanchonete = await prisma.lanchonete.create({
   *   data: {
   *     // ... data to create a Lanchonete
   *   }
   * })
   * 
   */
  create<T extends LanchoneteCreateArgs>(args: Prisma.SelectSubset<T, LanchoneteCreateArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Lanchonetes.
   * @param {LanchoneteCreateManyArgs} args - Arguments to create many Lanchonetes.
   * @example
   * // Create many Lanchonetes
   * const lanchonete = await prisma.lanchonete.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LanchoneteCreateManyArgs>(args?: Prisma.SelectSubset<T, LanchoneteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Lanchonetes and returns the data saved in the database.
   * @param {LanchoneteCreateManyAndReturnArgs} args - Arguments to create many Lanchonetes.
   * @example
   * // Create many Lanchonetes
   * const lanchonete = await prisma.lanchonete.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Lanchonetes and only return the `id`
   * const lanchoneteWithIdOnly = await prisma.lanchonete.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LanchoneteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LanchoneteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lanchonete.
   * @param {LanchoneteDeleteArgs} args - Arguments to delete one Lanchonete.
   * @example
   * // Delete one Lanchonete
   * const Lanchonete = await prisma.lanchonete.delete({
   *   where: {
   *     // ... filter to delete one Lanchonete
   *   }
   * })
   * 
   */
  delete<T extends LanchoneteDeleteArgs>(args: Prisma.SelectSubset<T, LanchoneteDeleteArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lanchonete.
   * @param {LanchoneteUpdateArgs} args - Arguments to update one Lanchonete.
   * @example
   * // Update one Lanchonete
   * const lanchonete = await prisma.lanchonete.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LanchoneteUpdateArgs>(args: Prisma.SelectSubset<T, LanchoneteUpdateArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Lanchonetes.
   * @param {LanchoneteDeleteManyArgs} args - Arguments to filter Lanchonetes to delete.
   * @example
   * // Delete a few Lanchonetes
   * const { count } = await prisma.lanchonete.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LanchoneteDeleteManyArgs>(args?: Prisma.SelectSubset<T, LanchoneteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lanchonetes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Lanchonetes
   * const lanchonete = await prisma.lanchonete.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LanchoneteUpdateManyArgs>(args: Prisma.SelectSubset<T, LanchoneteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lanchonetes and returns the data updated in the database.
   * @param {LanchoneteUpdateManyAndReturnArgs} args - Arguments to update many Lanchonetes.
   * @example
   * // Update many Lanchonetes
   * const lanchonete = await prisma.lanchonete.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Lanchonetes and only return the `id`
   * const lanchoneteWithIdOnly = await prisma.lanchonete.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LanchoneteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LanchoneteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lanchonete.
   * @param {LanchoneteUpsertArgs} args - Arguments to update or create a Lanchonete.
   * @example
   * // Update or create a Lanchonete
   * const lanchonete = await prisma.lanchonete.upsert({
   *   create: {
   *     // ... data to create a Lanchonete
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lanchonete we want to update
   *   }
   * })
   */
  upsert<T extends LanchoneteUpsertArgs>(args: Prisma.SelectSubset<T, LanchoneteUpsertArgs<ExtArgs>>): Prisma.Prisma__LanchoneteClient<runtime.Types.Result.GetResult<Prisma.$LanchonetePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Lanchonetes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteCountArgs} args - Arguments to filter Lanchonetes to count.
   * @example
   * // Count the number of Lanchonetes
   * const count = await prisma.lanchonete.count({
   *   where: {
   *     // ... the filter for the Lanchonetes we want to count
   *   }
   * })
  **/
  count<T extends LanchoneteCountArgs>(
    args?: Prisma.Subset<T, LanchoneteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LanchoneteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lanchonete.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LanchoneteAggregateArgs>(args: Prisma.Subset<T, LanchoneteAggregateArgs>): Prisma.PrismaPromise<GetLanchoneteAggregateType<T>>

  /**
   * Group by Lanchonete.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LanchoneteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LanchoneteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LanchoneteGroupByArgs['orderBy'] }
      : { orderBy?: LanchoneteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LanchoneteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLanchoneteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Lanchonete model
 */
readonly fields: LanchoneteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Lanchonete.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LanchoneteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Lanchonete model
 */
export interface LanchoneteFieldRefs {
  readonly id: Prisma.FieldRef<"Lanchonete", 'Int'>
  readonly nome: Prisma.FieldRef<"Lanchonete", 'String'>
  readonly imagemFundo: Prisma.FieldRef<"Lanchonete", 'String'>
  readonly imagemLogo: Prisma.FieldRef<"Lanchonete", 'String'>
  readonly utualizadaEm: Prisma.FieldRef<"Lanchonete", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Lanchonete findUnique
 */
export type LanchoneteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter, which Lanchonete to fetch.
   */
  where: Prisma.LanchoneteWhereUniqueInput
}

/**
 * Lanchonete findUniqueOrThrow
 */
export type LanchoneteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter, which Lanchonete to fetch.
   */
  where: Prisma.LanchoneteWhereUniqueInput
}

/**
 * Lanchonete findFirst
 */
export type LanchoneteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter, which Lanchonete to fetch.
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lanchonetes to fetch.
   */
  orderBy?: Prisma.LanchoneteOrderByWithRelationInput | Prisma.LanchoneteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lanchonetes.
   */
  cursor?: Prisma.LanchoneteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lanchonetes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lanchonetes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lanchonetes.
   */
  distinct?: Prisma.LanchoneteScalarFieldEnum | Prisma.LanchoneteScalarFieldEnum[]
}

/**
 * Lanchonete findFirstOrThrow
 */
export type LanchoneteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter, which Lanchonete to fetch.
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lanchonetes to fetch.
   */
  orderBy?: Prisma.LanchoneteOrderByWithRelationInput | Prisma.LanchoneteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lanchonetes.
   */
  cursor?: Prisma.LanchoneteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lanchonetes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lanchonetes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lanchonetes.
   */
  distinct?: Prisma.LanchoneteScalarFieldEnum | Prisma.LanchoneteScalarFieldEnum[]
}

/**
 * Lanchonete findMany
 */
export type LanchoneteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter, which Lanchonetes to fetch.
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lanchonetes to fetch.
   */
  orderBy?: Prisma.LanchoneteOrderByWithRelationInput | Prisma.LanchoneteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Lanchonetes.
   */
  cursor?: Prisma.LanchoneteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lanchonetes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lanchonetes.
   */
  skip?: number
  distinct?: Prisma.LanchoneteScalarFieldEnum | Prisma.LanchoneteScalarFieldEnum[]
}

/**
 * Lanchonete create
 */
export type LanchoneteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * The data needed to create a Lanchonete.
   */
  data: Prisma.XOR<Prisma.LanchoneteCreateInput, Prisma.LanchoneteUncheckedCreateInput>
}

/**
 * Lanchonete createMany
 */
export type LanchoneteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Lanchonetes.
   */
  data: Prisma.LanchoneteCreateManyInput | Prisma.LanchoneteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lanchonete createManyAndReturn
 */
export type LanchoneteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * The data used to create many Lanchonetes.
   */
  data: Prisma.LanchoneteCreateManyInput | Prisma.LanchoneteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lanchonete update
 */
export type LanchoneteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * The data needed to update a Lanchonete.
   */
  data: Prisma.XOR<Prisma.LanchoneteUpdateInput, Prisma.LanchoneteUncheckedUpdateInput>
  /**
   * Choose, which Lanchonete to update.
   */
  where: Prisma.LanchoneteWhereUniqueInput
}

/**
 * Lanchonete updateMany
 */
export type LanchoneteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Lanchonetes.
   */
  data: Prisma.XOR<Prisma.LanchoneteUpdateManyMutationInput, Prisma.LanchoneteUncheckedUpdateManyInput>
  /**
   * Filter which Lanchonetes to update
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * Limit how many Lanchonetes to update.
   */
  limit?: number
}

/**
 * Lanchonete updateManyAndReturn
 */
export type LanchoneteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * The data used to update Lanchonetes.
   */
  data: Prisma.XOR<Prisma.LanchoneteUpdateManyMutationInput, Prisma.LanchoneteUncheckedUpdateManyInput>
  /**
   * Filter which Lanchonetes to update
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * Limit how many Lanchonetes to update.
   */
  limit?: number
}

/**
 * Lanchonete upsert
 */
export type LanchoneteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * The filter to search for the Lanchonete to update in case it exists.
   */
  where: Prisma.LanchoneteWhereUniqueInput
  /**
   * In case the Lanchonete found by the `where` argument doesn't exist, create a new Lanchonete with this data.
   */
  create: Prisma.XOR<Prisma.LanchoneteCreateInput, Prisma.LanchoneteUncheckedCreateInput>
  /**
   * In case the Lanchonete was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LanchoneteUpdateInput, Prisma.LanchoneteUncheckedUpdateInput>
}

/**
 * Lanchonete delete
 */
export type LanchoneteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
  /**
   * Filter which Lanchonete to delete.
   */
  where: Prisma.LanchoneteWhereUniqueInput
}

/**
 * Lanchonete deleteMany
 */
export type LanchoneteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lanchonetes to delete
   */
  where?: Prisma.LanchoneteWhereInput
  /**
   * Limit how many Lanchonetes to delete.
   */
  limit?: number
}

/**
 * Lanchonete without action
 */
export type LanchoneteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lanchonete
   */
  select?: Prisma.LanchoneteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lanchonete
   */
  omit?: Prisma.LanchoneteOmit<ExtArgs> | null
}
