export const metadata = {
  title: "Lanchonete Page",
  description: "Generated by create next app",
};

import Home from "@/app/pageClient";

export default function HomeClient() {
  return <Home />;
}
